package dev.fitzgerald.entities;
//Object relational mapping
//use annotations to map an entity to a table in the database

import javax.persistence.*;

@Entity
@Table(name = "book")
public class Book {

    @Id  //field that is primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) //autogenerated by postgress
    @Column(name = "book_id")
    Integer id;
    @Column(name = "title")
    String title;
    @Column(name = "author")
    String author;
    @Column(name = "return_date")
    long returnDate;

    public Book() {
    }

    public Book(Integer id, String title, String author, long returnDate) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.returnDate = returnDate;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public long getReturnDate() {
        return returnDate;
    }

    public void setReturnDate(long returnDate) {
        this.returnDate = returnDate;
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                ", returnDate=" + returnDate +
                '}';
    }
}
